[[inputs.exec]]
  commands = ["./mristability.py"]
  timeout = "10s"
  data_format = "json"
  json_strict = true
  json_query = ""
  tag_keys = [
    "scanner",
    "coil",
    "filename"
  ]
  json_time_key = "timestamp"
  json_time_format = "unix"

